# Generated by Django 4.2.7 on 2024-10-05 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('course', models.IntegerField()),
                ('group', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'students',
            },
        ),
    ]
