# Generated by Django 4.2.7 on 2024-10-05 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='students',
            options={'managed': False},
        ),
    ]
