# Generated by Django 4.2.7 on 2024-10-05 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_students_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='students',
            options={},
        ),
    ]
