# Generated by Django 4.2.7 on 2024-10-05 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_students_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='debt_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
