# Generated by Django 4.2.7 on 2024-10-05 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_students_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='Черновик', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DecreeStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('decree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.decree')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.students')),
            ],
            options={
                'unique_together': {('decree', 'student')},
            },
        ),
        migrations.AddField(
            model_name='decree',
            name='students',
            field=models.ManyToManyField(through='app.DecreeStudents', to='app.students'),
        ),
    ]
