# Generated by Django 4.2.7 on 2024-10-08 22:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_decree_decreestudents_decree_students'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='decree',
            options={'ordering': ('-date_created',), 'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='decreestudents',
            options={'verbose_name': 'Связь студент-заявка', 'verbose_name_plural': 'Связи студент-заявка'},
        ),
        migrations.AddField(
            model_name='decree',
            name='moderator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decree_moderator', to=settings.AUTH_USER_MODEL, verbose_name='Модератор'),
        ),
        migrations.AddField(
            model_name='decree',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decree_owner', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='decree',
            name='date_created',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='decree',
            name='status',
            field=models.IntegerField(choices=[(1, 'Черновик'), (2, 'В работе'), (3, 'Завершена'), (4, 'Отклонена'), (5, 'Удалена')], default=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='decreestudents',
            name='decree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.decree', verbose_name='Заявка'),
        ),
        migrations.AlterField(
            model_name='decreestudents',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.students', verbose_name='Студент'),
        ),
        migrations.AlterModelTable(
            name='decree',
            table='decrees',
        ),
        migrations.AlterModelTable(
            name='decreestudents',
            table='decree_students',
        ),
    ]
